name: Create Release Asset

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Folder
        run: |
          mkdir WinCacheRemover
          cp WinCacheRemover.ps1 config.txt README.md LICENSE WinCacheRemover/
          zip -r WinCacheRemover.zip WinCacheRemover/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: WinCacheRemover.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
